// lib/shared/services/pin_service.dart
import 'dart:convert';
import 'dart:math';
import 'package:crypto/crypto.dart';

/// PIN hashing and verification service.
///
/// Security design:
/// - Each child gets a unique, randomly generated salt stored alongside
///   the PIN hash in Firestore (see [ChildModel.pinSalt]).
/// - SHA-256 is used for hashing.
/// - TODO (production): Replace SHA-256 with a proper password KDF such as
///   Argon2 or bcrypt for stronger resistance to brute-force attacks.
///   Dart has no built-in Argon2; consider a native plugin or server-side hashing.
class PinService {
  PinService._();

  static final _random = Random.secure();

  /// Generates a cryptographically random 16-byte salt as a hex string.
  /// Call once when creating a child profile; store the result in Firestore.
  static String generateSalt() {
    final bytes = List<int>.generate(16, (_) => _random.nextInt(256));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Hashes [pin] with the per-child [salt] using SHA-256.
  ///
  /// [salt] must be the value previously generated by [generateSalt].
  static String hashPin(String pin, {required String salt}) {
    final bytes = utf8.encode('$salt:$pin');
    return sha256.convert(bytes).toString();
  }

  /// Returns true if [pin] matches [pinHash] when hashed with [salt].
  static bool verifyPin(
    String pin,
    String pinHash, {
    required String salt,
  }) {
    return hashPin(pin, salt: salt) == pinHash;
  }
}
